language: python
python:
#  - "2.5" Not needed EL can use epel to upgrade to 2.6
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
# command to install dependencies
env:
#  - MONGO_VERSION=1.2.12
#  - MONGO_VERSION=1.3.2
#  - MONGO_VERSION=1.3.7
  - MONGO_VERSION=2.4.3

services: mongodb

before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install nmap -qq"
install:
  - "pip install pep8 --use-mirrors"
  - "pip install pyflakes --use-mirrors"
#  - "pip install boto --use-mirrors" # disabled: since boto not supporting py3
#  - "pip install pymongo sqlalchemy MySQL-python --use-mirrors" # disabled MySQL-python (not py3 compatible)
  - "pip install pymongo sqlalchemy pymysql --use-mirrors"
  - "pip install coveralls"
  - "python setup.py install"
before_script:
  - "pep8 . --exclude test,docs,examples"
  - "pyflakes ."
  - mysql -e 'create database poulet;'
script: nosetests --with-coverage --cover-package=libnmap
after_success:
  coveralls
